# Generated by Django 2.1.5 on 2020-04-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='comment_images')),
                ('date_made', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_made'],
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='trade_images')),
            ],
            options={
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(choices=[('art', 'Art'), ('books', 'Books'), ('clothes', 'Clothes'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('toys', 'Toys'), ('other', 'Other')], max_length=48)),
                ('quality', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('slightly-damaged', 'Slightly Damaged'), ('battle-scarred', 'Battle Scarred')], max_length=48)),
                ('description', models.TextField()),
                ('suggested_trade', models.CharField(max_length=128)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': [-4.28992174937531, 55.872480052801336]})),
                ('slug', models.SlugField()),
                ('date_made', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('picture', models.ImageField(blank=True, default='profile_images/default/default_profile_picture.png', upload_to='profile_images')),
                ('trades_made', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='trade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickswap.Trade'),
        ),
        migrations.AddField(
            model_name='comment',
            name='trade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quickswap.Trade'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
