# Generated by Django 2.1.5 on 2020-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickswap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_trades',
            field=models.ManyToManyField(to='quickswap.Trade'),
        ),
    ]
