# Generated by Django 2.1.5 on 2020-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickswap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.AlterField(
            model_name='trade',
            name='date_made',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
